### ISSUE TITLE
What's the principle of fusing the gps yaw?

### ISSUE THREAD

**Issue by keguo1119** [PX4/PX4-ECL#1028]
Hello!
    I am trying to understand the gps_yaw_fusion.cpp module and can't make it out that how the predicted_hdg comes?

`

               measured_hdg = _gps_sample_delayed.yaw + _gps_yaw_offset;

		// define the predicted antenna array vector and rotate into earth frame
		Vector3f ant_vec_bf = {cosf(_gps_yaw_offset), sinf(_gps_yaw_offset), 0.0f};
		Vector3f ant_vec_ef = _R_to_earth * ant_vec_bf;

		// check if antenna array vector is within 30 degrees of vertical and therefore unable to provide a reliable heading
		if (fabsf(ant_vec_ef(2)) > cosf(math::radians(30.0f)))  {
			return;
		}

		// calculate predicted antenna yaw angle
		predicted_hdg =  atan2f(ant_vec_ef(1),ant_vec_ef(0));`

**Comment by bresch** [comment]
Hi @keguo1119 ,
- `ant_vec_bf` is the orientation of the orientation of the GNSS antenna vector (two antennas are required; usually they are located "front-rear" or "left-right") on the drone, in body frame
- `ant_vec_ef` is the same vector but represented in the earth (local) frame axes (`_R_to_earth` is the rotation from body-to-earth)
- `predicted_hdg` is then simply the angle between the east and north components of this vector and represent the yaw angle that  the dual-GNSS antenna receiver should measure at this point in time

Hope that helped.

(This isn't an "issue" please use http://discuss.px4.io next time)
