### ISSUE TITLE
Estimate baro offset

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-ECL#44]
@priseborough This is to track the baro offset estimation.

**Comment by CarlOlsson** [comment]
[Here](http://logs.uaventure.com/view/npxmVkZpUTnGTGgEYFaQpU) is a log from a 4 minute flight which shows the baro drifting 1.4 meters.  What is also interesting is that the global position estimate drifted 2.4 meters, i.e. more than the sensor itself.

**Comment by tumbili** [comment]
@CarlOlsson  Even here, baro and the estimated height align really well and the innovations look normal.
I aligned the estimated height with the baro at the start of the log and swapped one sign to compare them.
![baro_lpz](https://cloud.githubusercontent.com/assets/7610489/18780162/87269aea-817c-11e6-9b1a-8256dbcc6a25.png)

**Comment by CarlOlsson** [comment]
@tumbili yes you are right that they align pretty good, but the estimate is still drifting more than the baro (due to accelerometer noise?), so if this is normal behavior maybe we could just decrease the baro noise to trust it more?

**Comment by priseborough** [comment]
@CarlOlsson If you do that then varying baro positional errors will cause larger changes in estimated height during manoeuvres or during transition in and out of ground effect. This is a compromise tune that needs to work across a wide range of setups.

**Comment by bresch** [comment]
Addressed by https://github.com/PX4/PX4-Autopilot/pull/17944
