### ISSUE TITLE
Timestamp audit

### ISSUE THREAD

**Issue by mhkabir** [PX4/PX4-ECL#504]
A lot of places in `control.cpp` seem to be using timestamps very arbitrarily, and this needs a thorough audit. Opening this issue to track down all places.

**Comment by mhkabir** [comment]
We need to differentiate more clearly between sensor disconnection (stale/old data) and sensor use inhibited due to failing checks. Currently these are used interchangeably. Additionally, a lot of comments are outdated and misleading.

**Comment by priseborough** [comment]
The use of timestamps has improved with the use of standardised helper functions.
