### ISSUE TITLE
Use vision position using gyro for yaw

### ISSUE THREAD

**Issue by hdiethelm** [PX4/PX4-ECL#567]
Hello,
I have a drone flying indoor using UWB for positioning. This works quite nice as long the compass is not drifting to much. Which is sadly mostly the case because of a bad compass and magnetic steel parts all around.
Because the flight time is short (3-4 min) I was thinking it should be possible to deactivate the compass and use just the gyro as reference for yaw.
So I set:
EKF2_AID_MASK to 24 (vision position / yaw)
EKF2_EVA_NOISE to 10 rad (Don't trust my yaw value sent over vision message at all which is sent as 0 to initialize yaw=0 at startup)
However, the estimated yaw value drifts quite a lot:
![att_fuse](https://user-images.githubusercontent.com/5688984/52119275-de2be500-2618-11e9-8382-ea6a9e8334ea.jpg)
while the integrated gyro value is stable and the integrated Z gyro shows a drift of just 2.5 deg:
![gyro_fuse](https://user-images.githubusercontent.com/5688984/52119294-ed129780-2618-11e9-835e-4ff55e67151a.jpg)

All values are in deg and deg/s. I did this tests while the drone was staying on my desk. At the beginning, I rotated it by 360 deg in 90 deg steps and back to test the gyro gain.

As a second try I commented out https://github.com/PX4/ecl/blob/1a1106878d6ab1cc48565bef9b25b07d626c5d0b/EKF/control.cpp#L324 to avoid heading fusion for yaw at all. However, the results are the same.

Is there a numerical problem or a bug? Did I miss some settings? Or is not avoidable by the way the Kalman filter works?

**Comment by hdiethelm** [comment]
Thanks!
I just did an other test: By forcing the gyro bias to zero, it gets better. But still, it seams that there is a bug because the integral of the gyro values is much more stable than the estimation.
```diff
diff --git a/EKF/control.cpp b/EKF/control.cpp
index f704168..3caf138 100644
--- a/EKF/control.cpp
+++ b/EKF/control.cpp
@@ -321,7 +321,7 @@ void Ekf::controlExternalVisionFusion()
 
 		// determine if we should use the yaw observation
 		if (_control_status.flags.ev_yaw) {
-			fuseHeading();
+			//fuseHeading();
 
 		}
 
diff --git a/EKF/ekf_helper.cpp b/EKF/ekf_helper.cpp
index 4246556..5940def 100644
--- a/EKF/ekf_helper.cpp
+++ b/EKF/ekf_helper.cpp
@@ -793,7 +793,7 @@ void Ekf::constrainStates()
 	}
 
 	for (int i = 0; i < 3; i++) {
-		_state.gyro_bias(i) = math::constrain(_state.gyro_bias(i), -0.349066f * _dt_ekf_avg, 0.349066f * _dt_ekf_avg);
+		_state.gyro_bias(i) = 0;
 	}
 
 	for (int i = 0; i < 3; i++) {
@@ -1196,7 +1196,7 @@ void Ekf::fuse(float *K, float innovation)
 	}
 
 	for (unsigned i = 0; i < 3; i++) {
-		_state.gyro_bias(i) = _state.gyro_bias(i) - K[i + 10] * innovation;
+		_state.gyro_bias(i) = 0;
 	}
 
 	for (unsigned i = 0; i < 3; i++) {
```

![att_no_fuse_no_bias](https://user-images.githubusercontent.com/5688984/52121719-e12ad380-2620-11e9-9be8-487942f51e40.jpg)

![gyro_no_fuse_no_bias](https://user-images.githubusercontent.com/5688984/52121725-e556f100-2620-11e9-81e2-d00a78208645.jpg)

Logs:
[logs.zip](https://github.com/PX4/ecl/files/2821436/logs.zip)

log_3_2019-2-1-11-40-30.ulg No fuseHeading
log_4_2019-2-1-11-59-38.ulg fuseHeading 10 rad noise
log_7_2019-2-1-12-41-10.ulg fuseHeading 10 rad noise / gyro bias = 0
log_9_2019-2-1-12-57-54.ulg No fuseHeading / gyro bias = 0

By the way: I'm using a pixracer temperature calibrated / PX4 stable

**Comment by hdiethelm** [comment]
I did an other test,  fuseHeading active and 10 rad noise. The drone was just standing on my desk, receiving zero as position and angle. At 291 s, something got out of control without any visible reason and yaw started drifting away. Meight be it was not visible before, because at about this time I rotated the drone.

![att_fuse2](https://user-images.githubusercontent.com/5688984/52124976-23591280-262b-11e9-8c44-75bc9e20a176.jpg)
![gyro_fuse2](https://user-images.githubusercontent.com/5688984/52124977-23591280-262b-11e9-8476-a8ac9a12fcaa.jpg)

[log_11_2019-2-1-13-58-16.zip](https://github.com/PX4/ecl/files/2821668/log_11_2019-2-1-13-58-16.zip)

**Comment by hdiethelm** [comment]
Last test for today: Same results on PX4 master branch:
![att_fuse_master](https://user-images.githubusercontent.com/5688984/52126265-2a821f80-262f-11e9-85ba-c55046aeeb9b.jpg)
![gyro_fuse_master](https://user-images.githubusercontent.com/5688984/52126272-2f46d380-262f-11e9-9c05-c19007c3be6b.jpg)
[log_12_2019-2-1-14-38-40.zip](https://github.com/PX4/ecl/files/2821773/log_12_2019-2-1-14-38-40.zip)

**Comment by mhkabir** [comment]
@priseborough can you please look into this.

**Comment by priseborough** [comment]
We can fly without a magnetometer with the current EKF using EKF2_MAG_TYPE=5. Also the updated covariance prediction enables smaller values of gyro bias process noise to be used to take advantage of IMU's that have  small thermal drift.
