### ISSUE TITLE
Yaw uncertainty is always initialized by mag parameter

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/PX4-ECL#587]
When investigating https://github.com/PX4/ecl/pull/586 I noticed that the yaw uncertainty is always initialized by the `mag_heading_noise` parameter even if no mag is used and the yaw measurement is coming from external vision. This is because `_control_status.flags.ev_yaw` is never set to true before EKF initialization is finished

**Comment by priseborough** [comment]
Current behaviour is to set the yaw uncertainty using the value for the yaw source being used for alignment at the time.
