### ISSUE TITLE
TECS initializing states after time slip

### ISSUE THREAD

**Issue by hannahdn** [PX4/PX4-ECL#660]
The _initialize_states function is supposed to reinitialize the states after a large time slip:

`        if (_pitch_update_timestamp == 0 || _dt > DT_MAX || !_in_air || !_states_initalized) {`

However that function is called after _dt is constrained to be lower than DT_MAX. In the case of an "actual" _dt larger than DT_MAX, the states are not reinitialized. This could be a problem when there is a longer update time of the position controller, due to EKF lagging / resetting for instance, but during which the aircraft stays in auto or position mode.

```
void TECS::update_pitch_throttle(const matrix::Dcmf &rotMat, float pitch, float baro_altitude, float hgt_setpoint,
 float EAS_setpoint, float indicated_airspeed, float eas_to_tas, bool climb_out_setpoint, float pitch_min_climbout,
 float throttle_min, float throttle_max, float throttle_cruise, float pitch_limit_min, float pitch_limit_max, float dalt_rate_limit)
{
        // Calculate the time since last update (seconds)
        uint64_t now = ecl_absolute_time();
        _dt = constrain((now - _pitch_update_timestamp) * 1e-6f, DT_MIN, DT_MAX);

```
// Set class variables from inputs
_throttle_setpoint_max = throttle_max;
_throttle_setpoint_min = throttle_min;
_pitch_setpoint_max = pitch_limit_max;
_pitch_setpoint_min = pitch_limit_min;
_climbout_mode_active = climb_out_setpoint;
```

    // Initialize selected states and variables as required
    _initialize_states(pitch, throttle_cruise, baro_altitude, pitch_min_climbout, eas_to_tas);```

**Comment by kamilritz** [comment]
I am not sure who is maintaining this. @priseborough can you help here?
@hannahdn Do you have certain solution in mind, that you could share as a pull request?

**Comment by hannahdn** [comment]
Yes, I'll get a pull request out for review this week.

**Comment by bresch** [comment]
fixed by https://github.com/PX4/PX4-Autopilot/pull/16943
