### ISSUE TITLE
Move PX4/Firmware/src/modules/controllib into ecl

### ISSUE THREAD

**Issue by jgoppert** [PX4/PX4-ECL#68]
Ecl and PX4/Firmware/src/modules/controllib have the same design and same purpose and should be combined. Basically all control blocks look like:

y = update(u)

With matrix lib we can even make all of these blocks in vector versions.
The controllib is set up similar to simulink. Each block has a set of parameters which form its context, and these blocks can be nested. When you call you call y = update(u), then the super block, can call update on all required subblocks to produce the output.

The parameter backend of the contorllib is currently tied to px4 internals, but this would be very easy to switch by modifying the controllib/blocks/Block.hpp

@tumbili @LorenzMeier @priseborough

**Comment by dagar** [comment]
Can you expand on this a bit? What would the "param" backend look like?
