### ISSUE TITLE
GPS/VIO yaw aiding without mag not possible

### ISSUE THREAD

**Issue by bresch** [PX4/PX4-ECL#800]
From: https://discuss.px4.io/t/possible-to-initialize-ekf-without-mag-sensor/16115

- [x] EKF2 needs magnetometer data to initialize, even if `EKF2_MAG_TYPE` is set to none (https://github.com/PX4/ecl/blob/2fa43419d2bd7319024682b311f52c78f9a86f52/EKF/ekf.cpp#L181-L184)
- [x] When not using mag (TYPE == none), we artificially fuse zero innovations to constrain the variance growth and help with gyro learning. If we're fusing GPS/VIO yaw data, this isn't required https://github.com/PX4/ecl/blob/47624a0f021e2c187cc4763ad829afe2aa4fb11a/EKF/mag_control.cpp#L49-L56

**Comment by mhkabir** [comment]
@dagar I remember I brought this up a few months back, and we collected it in a Google doc. Do you have a link to that doc?

**Comment by dagar** [comment]
> @dagar I remember I brought this up a few months back, and we collected it in a Google doc. Do you have a link to that doc?

Shared on slack.

**Comment by priseborough** [comment]
These issues appear to be addressed in upstream master at 8aecc64
