### ISSUE TITLE
High vibration -> insane altitude -> shoot-up in altitude mode. Could it be prevented?

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/PX4-ECL#832]
I flew a QAV250 and crashed because of unrelated problems. When I tried to fly with it again after the crash the vibration levels were quite a bit higher for invisible mechanical reasons but it still flew ok-ish in stabilized. When I switched to Altitude I got a heart attack because it shut up into the air with full thrust. Apparently the altitude estimate diverged and that might be expected given the sensor measurements but my question would be could it have been automatically prevented since the estimate went insane looking at the log but I could still "use" it to switch to altitude mode.

![image](https://user-images.githubusercontent.com/4668506/83265371-b70c0600-a1c1-11ea-88c1-f7066c82d044.png)

https://logs.px4.io/plot_app?log=79083ce8-35ca-4f2f-9e32-0c1addc1da3c

FYI @bresch

**Comment by dagar** [comment]
We could do something if the accel is experience continuous clipping.

![Screenshot from 2020-05-29 14-45-50](https://user-images.githubusercontent.com/84712/83294320-216d7800-a1bb-11ea-8aed-89a1bc83a57b.png)


The vibration metric might be another idea.

![Screenshot from 2020-05-29 14-47-05](https://user-images.githubusercontent.com/84712/83294437-4eba2600-a1bb-11ea-92a1-966b8b7476d0.png)

**Comment by dagar** [comment]
Can we flag vertical position/velocity validity?

![Screenshot from 2020-05-29 14-59-25](https://user-images.githubusercontent.com/84712/83295507-14518880-a1bd-11ea-94f8-7bdd194f6ba2.png)
![Screenshot from 2020-05-29 15-01-20](https://user-images.githubusercontent.com/84712/83295627-47941780-a1bd-11ea-908b-bd85eba3605b.png)

**Comment by priseborough** [comment]
Current code already increases IMU accel process noise when clipping occurs and shortens reset time. Also new covariance prediction equations are more robust so this is likely improved. Vertical position and velocity validity z_valid and vz_valid are currently checked pre-flight using the preFlightCheckHeightFailed and preFlightCheckVertVelFailed functions, but not during flight.

From memory the reason for not checking innovations  during flight and changing validity was that this would cause the controller to fallback to a manual throttle (no height control) mode. We can change the way this is reported, but need to coordinate with changes in commander.

**Comment by garlinplus** [comment]
![image](https://user-images.githubusercontent.com/12841057/153119760-a15f33f6-3bc7-492c-ac0f-04dabab79d0a.png)
From above picture,it can be found that your imu az is error compared with az of gps vd derivative.

**Comment by bresch** [comment]
Since the update on the covariance prediction derivation, I didn't see such divergence due to high vibrations and moderate clipping anymore. Let's close this issue and re-open one if we encounter the problem again.
