### ISSUE TITLE
Run GenerateNavFilterEquations.m error

### ISSUE THREAD

**Issue by BreederBai** [PX4/PX4-ECL#903]
matlab version:2020a

![image](https://user-images.githubusercontent.com/27894314/91245172-10afac80-e780-11ea-9f65-4e813ff01bd3.png)

**Comment by xdwgood** [comment]
I suggest you use the python version of the derivation：　https://github.com/PX4/ecl/blob/master/EKF/python/ekf_derivation/main.py

**Comment by BreederBai** [comment]
@xdwgood Is there any instructions for the python version?

**Comment by xdwgood** [comment]
I use python3.6,and work fine

**Comment by bresch** [comment]
Closing as the Matlab derivation is no longer used.
