### ISSUE TITLE
Unsuitable GPS yaw fusion stopping criteria

### ISSUE THREAD

**Issue by lukegluke** [PX4/PX4-ECL#905]
Here
https://github.com/PX4/ecl/blob/264c8c4e8681704e4719d0a03b848df8617c0863/EKF/control.cpp#L718-L725
if gps yaw is not fused for 5 seconds it is marked as faulty, GPS yaw fusion get stopped and **will never be fused again** until reboot (ekf2 restart).
It easily to loose gps just for 5 seconds passing under bridge construction for example. It is very realistic case. But now it is no matter if gps heading get recovered and available again then, estimator will not perform GPS yaw fusion anymore.

Another case (more theoretical and for special vehicles) - if vehicle like jet plane take up pitching within 30 degrees of vertical (so gps heading reasonably unable to provide a reliable heading) for those 5 seconds, ekf will also turn off GPS yaw fusion forever.
https://github.com/PX4/ecl/blob/264c8c4e8681704e4719d0a03b848df8617c0863/EKF/gps_yaw_fusion.cpp#L64-L67

**Comment by bresch** [comment]
fixed by https://github.com/PX4/PX4-ECL/pull/1006 and https://github.com/PX4/PX4-Autopilot/pull/18015
