### ISSUE TITLE
extVisionSample limited covariance

### ISSUE THREAD

**Issue by WysokiStudent** [PX4/PX4-ECL#915]
PX4 accepts ROS nav_msgs/Odometry messages and distributes them as vehicle_visual_odometry. The Odometry messages provide covariance for position, velocity, angular velocity and rotation. EKF uses most of the provided information with one exception. Out of the rotation covariance only yaw variance is used. What is the rationale behind this? Also extVisionSample seems to disregard position-rotation covariance as well, why is that?

**Comment by priseborough** [comment]
We only use the yaw information from the attitude. We use position-velocity covariance, but yaw is used as an independent observation in a different part of the code due to historical reasons.
