### ISSUE TITLE
Implementing a reset ekf function. Issue with thread?

### ISSUE THREAD

**Issue by weiyuhe** [PX4/PX4-ECL#966]
Hi, I am trying to implement a reset_ekf() function inside ekf.cpp. My plan is to create an orb topic called ekf_reset, subscribe to it in ekf2_main.cpp, and the reset_ekf() function will be triggered every time I send a message to the ekf_reset topic. I am getting a strange bug where some variables, like _state.pos, will reset itself after the reset_ekf() function, but then it will go back to the pre-reset value. It almost felt like two threads are running at the same time; one thread did reset the variable, but the other thread did not. 

Any advice will be great! Thank you in advance.

**Comment by dagar** [comment]
It's hard to say without seeing any code or data, but I think it's useful functionality to add. If you open a PR adding a reset method in the EKF backend (this repo), then in PX4-Autopilot ekf2 we can add a `vehicle_command` or  other mechanism to initiate the reset. From there we can debug and add testing to make sure it actually works.
