### ISSUE TITLE
Potential division-by-zero in EKFGSF_yaw.cpp

### ISSUE THREAD

**Issue by wuruoyu** [PX4/PX4-ECL#983]
**Describe the bug**
There is a potential division-by-zero exception in the following code

https://github.com/PX4/PX4-ECL/blob/098d5ce5c034f630b1b440a02ba78a13d092b8c7/EKF/EKFGSF_yaw.cpp#L104-L119

In line 119 there is `(unmodified_weights_sum - _weight_min)` as the denominator. It is possible to be zero when there is only one model that has their weights equal to `_weight_min`, and all the others have their weights less than `_weight_min`. In this scenario, `unmodified_weights_sum == weight_min`, and the division-by-zero exception happens. 

**Expected behavior**
A guarding check before the division would be preferred here.

**Comment by priseborough** [comment]
Given we have never needed to set the value of the _weight_min constant to a non zero value though development and subsequent testing, that entire block of code controlled by 

if (_weight_min > FLT_EPSILON) { 

has never run and should  be removed.
